
services:
  # The PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # The Node.js Backend Service
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./.env
    ports:
      # Expose the container's port 3001 to the VM's port 3001
      # This is for your Argo Tunnel to connect to.
      - "3001:3001"
    depends_on:
      - postgres

  # The React Frontend Service (served with Nginx)
  frontend:
    build: ./frontend
    restart: always
    ports:
      # Expose the container's port 80 to the VM's port 8281 (as you specified)
      - "8281:80"
    depends_on:
      - backend

volumes:
  pgdata: # This named volume will persist your database data